-- MySQL Script generated by MySQL Workbench
-- Wed Jul 28 00:56:44 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema zoom-meetings
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `zoom-meetings` ;

-- -----------------------------------------------------
-- Schema zoom-meetings
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `zoom-meetings` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci ;
USE `zoom-meetings` ;

-- -----------------------------------------------------
-- Table `zoom-meetings`.`attendees`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zoom-meetings`.`attendees` ;

CREATE TABLE IF NOT EXISTS `zoom-meetings`.`attendees` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `meeting_id` VARCHAR(45) NOT NULL,
  `user_id` VARCHAR(45) NULL DEFAULT NULL,
  `isHost` TINYINT NULL DEFAULT NULL,
  `isAllowed` TINYINT NULL DEFAULT NULL,
  `isLive` TINYINT NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `meeting-attendee_idx` (`meeting_id` ASC) VISIBLE,
  CONSTRAINT `a-belgongs-to-m`
    FOREIGN KEY (`meeting_id`)
    REFERENCES `zoom-meetings`.`meetings` (`meeting_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci
COMMENT = '	f';


-- -----------------------------------------------------
-- Table `zoom-meetings`.`meetings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zoom-meetings`.`meetings` ;

CREATE TABLE IF NOT EXISTS `zoom-meetings`.`meetings` (
  `meeting_id` VARCHAR(45) NOT NULL,
  `zoom_id` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `join_url` VARCHAR(45) NOT NULL,
  `createdBy` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`meeting_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
